version: "3"
services:
  namenode:
    image: karton91/hadoop_namenode
    container_name: namenode
    hostname: 172.28.0.2
    volumes:
      - ./hadoop_resources/namenode:/var/data/hadoop/hdfs/
    environment:
      - CLUSTER_NAME=hadoop
    env_file:
      - ./hadoop.env
    networks:
      hadoopnet:
        ipv4_address: 172.28.0.2
  
  resourcemanager:
    image: karton91/hadoop_resourcemanager
    container_name: resourcemanager
    depends_on:
      - namenode
      - datanode1
      - datanode2
    env_file:
      - ./hadoop.env
    networks:
      hadoopnet:
        ipv4_address: 172.28.0.3

  historyserver:
    image: karton91/hadoop_historyserver
    container_name: historyserver
    depends_on:
      - namenode
      - datanode1
      - datanode2
    volumes:
      - ./hadoop_resources/historyserver:/var/history/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    networks:
      hadoopnet:
        ipv4_address: 172.28.0.4

  nodemanager:
    image: karton91/hadoop_nodemanager
    container_name: nodemanager
    depends_on:
      - namenode
      - datanode1
      - datanode2
    env_file:
      - ./hadoop.env
    networks:
      hadoopnet:
        ipv4_address: 172.28.0.5
  
  datanode1:
    image: karton91/hadoop_datanode
    container_name: datanode1
    hostname: 172.28.0.6
    depends_on:
      - namenode
    volumes:
      - ./hadoop_resources/datanode1:/var/data/hadoop/hdfs/
    env_file:
      - ./hadoop.env
    networks:
      hadoopnet:
        ipv4_address: 172.28.0.6
  
  datanode2:
    image: karton91/hadoop_datanode
    container_name: datanode2
    hostname: 172.28.0.7
    depends_on:
      - namenode
    volumes:
      - ./hadoop_resources/datanode2:/var/data/hadoop/hdfs/
    env_file:
      - ./hadoop.env
    networks:
      hadoopnet:
        ipv4_address: 172.28.0.7
  
  datanode3:
    image: karton91/hadoop_datanode
    container_name: datanode3
    hostname: 172.28.0.8
    depends_on:
      - namenode
    volumes:
      - ./hadoop_resources/datanode3:/var/data/hadoop/hdfs/
    env_file:
      - ./hadoop.env
    networks:
      hadoopnet:
        ipv4_address: 172.28.0.8

networks:
  hadoopnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.28.0.0/28

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_datanode3:
  hadoop_historyserver: