version: "3"
services:
  namenode:
    image: karton91/hadoop_namenode
    container_name: namenode
    hostname: namenode
    volumes:
      - ./hadoop_resources/namenode/hdfs:/var/data/hadoop/hdfs/
      - ./hadoop_resources/namenode/log:/var/log/hadoop/
    environment:
      - CLUSTER_NAME=hadoop
    env_file:
      - ./hadoop.env
    networks:
      kafkaNet:
        ipv4_address: 172.28.0.2
  
  resourcemanager:
    image: karton91/hadoop_resourcemanager
    container_name: resourcemanager
    hostname: resourcemanager
    depends_on:
      - namenode
    volumes:
      - ./hadoop_resources/resourcemanager/log:/var/log/hadoop/
    env_file:
      - ./hadoop.env
    networks:
      kafkaNet:
        ipv4_address: 172.28.0.3

  historyserver:
    image: karton91/hadoop_historyserver
    container_name: historyserver
    hostname: historyserver
    depends_on:
      - namenode
    volumes:
      - ./hadoop_resources/historyserver/log:/var/log/hadoop/
    env_file:
      - ./hadoop.env
    networks:
      kafkaNet:
        ipv4_address: 172.28.0.4

  checkpointnode:
    image: karton91/hadoop_checkpointnode
    container_name: checkpointnode
    hostname: checkpointnode
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
      - nodemanager
    volumes:
      - ./hadoop_resources/checkpointnode/hdfs:/var/data/hadoop/hdfs/
      - ./hadoop_resources/checkpointnode/log:/var/log/hadoop/
    env_file:
      - ./hadoop.env
    networks:
      kafkaNet:
        ipv4_address: 172.28.0.5

  nodemanager:
    image: karton91/hadoop_nodemanager
    container_name: nodemanager
    hostname: nodemanager
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
    volumes:
      - ./hadoop_resources/nodemanager/log:/var/log/hadoop/
    env_file:
      - ./hadoop.env
    networks:
      kafkaNet:
        ipv4_address: 172.28.0.6

  proxyserver:
    image: karton91/hadoop_proxyserver
    container_name: proxyserver
    hostname: proxyserver
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
    volumes:
      - ./hadoop_resources/proxyserver/log:/var/log/hadoop/
    env_file:
      - ./hadoop.env
    networks:
      kafkaNet:
        ipv4_address: 172.28.0.7
  
  datanode1:
    image: karton91/hadoop_datanode
    container_name: datanode1
    hostname: datanode1
    depends_on:
      - namenode
    volumes:
      - ./hadoop_resources/datanode1/hdfs:/var/data/hadoop/hdfs/
      - ./hadoop_resources/datanode1/log:/var/log/hadoop/
    env_file:
      - ./hadoop.env
    networks:
      kafkaNet:
        ipv4_address: 172.28.0.8
  
  datanode2:
    image: karton91/hadoop_datanode
    container_name: datanode2
    hostname: datanode2
    depends_on:
      - namenode
    volumes:
      - ./hadoop_resources/datanode2/hdfs:/var/data/hadoop/hdfs/
      - ./hadoop_resources/datanode2/log:/var/log/hadoop/
    env_file:
      - ./hadoop.env
    networks:
      kafkaNet:
        ipv4_address: 172.28.0.9
  
  datanode3:
    image: karton91/hadoop_datanode
    container_name: datanode3
    hostname: datanode3
    depends_on:
      - namenode
    volumes:
      - ./hadoop_resources/datanode3/hdfs:/var/data/hadoop/hdfs/
      - ./hadoop_resources/datanode3/log:/var/log/hadoop/
    env_file:
      - ./hadoop.env
    networks:
      kafkaNet:
        ipv4_address: 172.28.0.10
  zoo1:
    image: karton91/zoo1
    container_name: zoo1
    hostname: zoo1
    volumes:
      - ./zookeeper_resources/zoo1/log:/var/log/zookeeper/
      - ./zookeeper_resources/zoo1/data:/var/data/zookeeper/
    env_file:
      - ./hadoop.env
    networks:
      kafkaNet:
        ipv4_address: 172.28.0.11
  zoo2:
    image: karton91/zoo2
    container_name: zoo2
    hostname: zoo2
    volumes:
      - ./zookeeper_resources/zoo2/log:/var/log/zookeeper/
      - ./zookeeper_resources/zoo2/data:/var/data/zookeeper/
    env_file:
      - ./hadoop.env
    networks:
      kafkaNet:
        ipv4_address: 172.28.0.12
  zoo3:
    image: karton91/zoo3
    container_name: zoo3
    hostname: zoo3
    volumes:
      - ./zookeeper_resources/zoo3/log:/var/log/zookeeper/
      - ./zookeeper_resources/zoo3/data:/var/data/zookeeper/
    env_file:
      - ./hadoop.env
    networks:
      kafkaNet:
        ipv4_address: 172.28.0.13
  kafka1:
    image: karton91/kafka1
    container_name: kafka1
    hostname: kafka1
    volumes:
      - ./kafka_resources/kafka1/log:/var/log/kafka/
    env_file:
      - ./hadoop.env
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      kafkaNet:
        ipv4_address: 172.28.0.14
  kafka2:
    image: karton91/kafka2
    container_name: kafka2
    hostname: kafka2
    volumes:
      - ./kafka_resources/kafka2/log:/var/log/kafka/
    env_file:
      - ./hadoop.env
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      kafkaNet:
        ipv4_address: 172.28.0.15
  kafka3:
    image: karton91/kafka3
    container_name: kafka3
    hostname: kafka3
    volumes:
      - ./kafka_resources/kafka3/log:/var/log/kafka/
    env_file:
      - ./hadoop.env
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      kafkaNet:
        ipv4_address: 172.28.0.16

networks:
  kafkaNet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.28.0.0/24
