FROM karton91/hadoop_base
MAINTAINER Ruben Garrido <ruben.garrido1@um.es>

USER root

ADD spark-2.3.0-bin-hadoop2.7.tgz /opt/spark-2.3.0-bin-hadoop2.7.tgz

RUN mkdir -p /opt/bd/streaming/

RUN cd /opt/bd/streaming/ && \
	cp -R spark-2.3.0-bin-hadoop2.7.tgz/spark-2.3.0-bin-hadoop2.7 spark-2.3.0-bin-hadoop2.7 && \
	rm -R spark-2.3.0-bin-hadoop2.7.tgz && \
	ln -s spark-2.3.0-bin-hadoop2.7 spark

RUN chown -R hdmaster:hadoop /opt/spark-2.3.0-bin-hadoop2.7
RUN chown -R hdmaster:hadoop /opt/spark/

RUN mv /opt/bd/streaming/spark/conf/spark-defaults.conf.template /opt/bd/streaming/spark/conf/spark-defaults.conf
RUN echo "" >> /opt/spark/conf/spark-defaults.conf
RUN echo "spark.master                       yarn" >> /opt/bd/streaming/spark/conf/spark-defaults.conf
RUN echo "spark.driver.memory                512m" >> /opt/bd/streaming/spark/conf/spark-defaults.conf
RUN echo "spark.yarn.am.memory               512m" >> /opt/bd/streaming/spark/conf/spark-defaults.conf
RUN echo "spark.executor.memory              512m" >> /opt/bd/streaming/spark/conf/spark-defaults.conf

RUN chown -R hdmaster:hadoop /opt/bd/streaming/spark/conf/

ADD  Default_Conf/AddHosts2 /
RUN cat /AddHosts2 >> AddHosts

	
ENV SPARK_HOME /opt/spark
ENV LD_LIBRARY_PATH /opt/bd/hadoop/lib/native
ENV PATH=$PATH:$SPARK_HOME/bin
RUN echo export SPARK_HOME=/opt/spark  >> /opt/bd/.bashrc
RUN echo export LD_LIBRARY_PATH=/opt/bd/hadoop/lib/native >> /opt/bd/.bashrc
RUN echo export PATH='$PATH':$SPARK_HOME/bin >> /opt/bd/.bashrc


ADD run.sh /run.sh
RUN chmod a+x /run.sh


CMD ["/run.sh"]

# Based on https://linode.com/docs/databases/hadoop/install-configure-run-spark-on-top-of-hadoop-yarn-cluster/